### ISSUE TITLE
matchers.go:335:19: undefined: matchers.HaveExactElementsMatcher

### ISSUE THREAD

**Issue by monkey92t** [bsm/gomega#2]
cp from go-redis:

../../../go/pkg/mod/github.com/bsm/gomega@v1.27.7/matchers.go:335:19: undefined: matchers.HaveExactElementsMatcher

**Comment by monkey92t** [comment]
@dim

**Comment by dim** [comment]
Ooops, solved in https://github.com/bsm/gomega/releases/tag/v1.27.7.1
